homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Stockholm
  #customize: 
  customize_glob:
    switch.relay*:
      hidden: true
    light.knapp*:
      hidden: true

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Include dirs
zone: !include_dir_merge_list includes/zone
sensor: !include_dir_merge_list includes/sensors
group: !include_dir_merge_named includes/groups
#light: !include_dir_merge_list includes/lights
switch: !include_dir_merge_list includes/switches
scene: !include_dir_merge_list includes/scenes
script: !include_dir_merge_list includes/scripts
automation: !include_dir_merge_list includes/automations

http:
  api_password: !secret http_password

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key

# Hardware
arduino:
  port: /dev/ttyUSB1

rfxtrx:
  device: /dev/ttyUSB0

volvooncall:
  username: !secret voc_username
  password: !secret voc_password

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  keepalive: 60

mqtt_eventstream:
  subscribe_topic: slaves/#
  publish_topic: master

media_player:
  - platform: plex
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_secret

device_tracker:
  - platform: asuswrt
    host: !secret asus_router_host
    username: !secret asus_router_username
    ssh_key: !secret ssh_key_path
    track_new_devices: false

remote:
  - platform: harmony
    name: Livingroom
    host: !secret harmony_host
