homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Stockholm
  #customize:
  customize_glob:
    "*.*":
      custom_ui_state_card: custom-ui  
    group.volvooncall_dashboard:
      state_card_mode: badges
      badges_list:
        - binary_sensor.neh575_brake_fluid
        - binary_sensor.neh575_bulbs
        - binary_sensor.neh575_service
        - binary_sensor.neh575_washer_fluid
        - binary_sensor.neh575_doors
        - binary_sensor.neh575_windows
    binary_sensor.neh575_brake_fluid:
      hidden_in:
        - group.volvooncall_dashboard
    binary_sensor.neh575_bulbs:
      hidden_in:
        - group.volvooncall_dashboard
    binary_sensor.neh575_service:
      hidden_in:
        - group.volvooncall_dashboard
    binary_sensor.neh575_washer_fluid:
      hidden_in:
        - group.volvooncall_dashboard
    binary_sensor.neh575_doors:
      hidden_in:
        - group.volvooncall_dashboard
    binary_sensor.neh575_windows:
      hidden_in:
        - group.volvooncall_dashboard
    light.*:
      custom_ui_state_card: custom-ui
      state_card_mode: break-slider
      stretch_slider: true
      hide_control: false
      show_last_changed: false
      slider_theme:
        min: 10
        max: 255
        pin: true
        off_when_min: true
        report_when_not_changed: false
    switch.relay*:
      hidden: true
    light.knapp*:
      hidden: true

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Include dirs
zone: !include_dir_merge_list includes/zone
sensor: !include_dir_merge_list includes/sensors
group: !include_dir_merge_named includes/groups
#light: !include_dir_merge_list includes/lights
switch: !include_dir_merge_list includes/switches
scene: !include_dir_merge_list includes/scenes
script: !include_dir_merge_list includes/scripts
automation: !include_dir_merge_list includes/automations

http:
  api_password: !secret http_password
  base_url: !secret http_host
  use_x_forwarded_for: true
  cors_allowed_origins:
    - https://google.com
    - https://home-assistant.io
  trusted_networks: 
    - 127.0.0.1

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google
  language: 'sv'

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key

# Hardware
arduino:
  port: /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0

rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1QC1DY-if00-port0

volvooncall:
  username: !secret voc_username
  password: !secret voc_password

# android_ip_webcam:
#   host: !secret android_cam_ip
#   username: !secret android_cam_usr
#   password: !secret android_cam_pw
#   sensors:
#     - motion

light:
  - platform: hue
    host: 127.0.0.1
    filename: deconz

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  keepalive: 60

mqtt_eventstream:
  subscribe_topic: slaves/#
  publish_topic: master

media_player:
  - platform: plex
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_secret

device_tracker:
  - platform: asuswrt
    host: !secret asus_router_host
    username: !secret asus_router_username
    ssh_key: !secret ssh_key_path
    track_new_devices: false

remote:
  - platform: harmony
    name: Livingroom
    host: !secret harmony_host

ifttt:
  key: !secret ifttt_api